apiVersion: v2
name: cronjob
description: A Helm chart for deploying CronJobs on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Ashwath Abraham Stephen
    email: ashwathstephen@gmail.com
keywords:
  - cronjob
  - scheduled
  - kubernetes
home: https://github.com/ashwathstephen/kubernetes-helm-charts

