apiVersion: v2
name: microservice
description: A production-ready Helm chart for deploying microservices on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Ashwath Abraham Stephen
    email: ashwathstephen@gmail.com
keywords:
  - microservice
  - deployment
  - kubernetes
  - production
home: https://github.com/ashwathstephen/kubernetes-helm-charts
sources:
  - https://github.com/ashwathstephen/kubernetes-helm-charts

