apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset.fullname" . }}
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "statefulset.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.headless }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset.fullname" . }}-headless
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "statefulset.selectorLabels" . | nindent 4 }}
{{- end }}

