apiVersion: v2
name: statefulset
description: A Helm chart for deploying StatefulSets on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Ashwath Abraham Stephen
    email: ashwathstephen@gmail.com
keywords:
  - statefulset
  - database
  - persistent
  - kubernetes
home: https://github.com/ashwathstephen/kubernetes-helm-charts

